## @file
# Azure Pipeline build file to build and test code in this repo.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

trigger:
- main

pr:
- main

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

jobs:
  - job: BuildAndTest
    displayName: Build and Test

    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        windows:
          imageName: 'windows-latest'

    pool:
      vmImage: $(imageName)

    container:
      image: $[ if(eq(variables['vmImage'], 'ubuntu-latest')) { 'ghcr.io/microsoft/mu_devops/ubuntu-22-build:latest' } ]

    workspace:
      clean: all

    steps:
    - checkout: self
      fetchDepth: 1
      clean: true

    - template: Steps/RustSetupSteps.yml@mu_devops
    - template: Steps/RustCargoSteps.yml@mu_devops
